import Header from "@/components/Header";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col bg-slate-900 min-h-screen h-full">
        <Header/>
        <p className="mt-16 text-red-300 font-bold">Hello world!</p>
      </main>
    </>
  );
}
